### ISSUE TITLE
Mysterious exit code 1

### ISSUE THREAD

**Issue by jasonkuhrt** [iynere/compare-url#21] opened 2019-04-19 13:47 UTC
### Orb version

`0.4.10`

### What happened

Branch off master, push an insignificant change, exits 1

Has happened twice to me.

- First time I fixed it by updating to latest version of orb.
- Second time (this time) I fixed it by setting `debug: true`. Then I removed `debug: true` and it continued to work.

```
checking if fix/base-bash-safe-export is a new branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  112k  100  112k    0     0  1120k      0 --:--:-- --:--:-- --:--:-- 1122k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 72190  100 72190    0     0   570k      0 --:--:-- --:--:-- --:--:--  573k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 54585  100 54585    0     0   586k      0 --:--:-- --:--:-- --:--:--  592k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 73775  100 73775    0     0   744k      0 --:--:-- --:--:-- --:--:--  750k
----------------------------------------------------------------------------------------------------
yes, fix/base-bash-safe-export is new and 667069510cd23599dde2c590a0f3ce5e5d07a2ed is its only commit
finding most recent ancestor commit from any other branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 54585  100 54585    0     0   479k      0 --:--:-- --:--:-- --:--:--  484k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 54585  100 54585    0     0   635k      0 --:--:-- --:--:-- --:--:--  642k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 73775  100 73775    0     0   891k      0 --:--:-- --:--:-- --:--:--  900k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 73775  100 73775    0     0   460k      0 --:--:-- --:--:-- --:--:--  461k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 75923  100 75923    0     0   503k      0 --:--:-- --:--:-- --:--:--  500k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 75923  100 75923    0     0   748k      0 --:--:-- --:--:-- --:--:--  756k
Exited with code 1
```

### Expected behavior

Branch off master, push an insignificant change, exits 0.

Related:

- https://github.com/iynere/compare-url/issues/11
- https://github.com/iynere/compare-url/issues/17

**Comment by jasonkuhrt** [comment] 2019-04-19 14:37
More info:

![image](https://user-images.githubusercontent.com/284476/56428895-ff52b800-628e-11e9-8f74-7c9f10ad62ea.png)

It happened twice more to me this morning. It always happens on the first built commit of a new PR. In the above screenshot, the fix was to push an empty commit `git commit --allow-empty ...`.

**Comment by Fumler** [comment] 2019-04-29 11:37
Same issue.

**Comment by yinzara** [comment] 2019-05-07 18:37
This is actually a duplicate of #19

**Comment by jasonkuhrt** [comment] 2019-05-08 01:23
The issue is here I think https://github.com/iynere/compare-url/blob/master/src/commands/reconstruct.yml#L165-L167. Note how the exit code is not `||`'d, so naturally it will lead to an actual exit, not caught.

**Comment by iamnader** [comment] 2019-05-11 18:23
@iynere would be awesome to get this merged!

**Comment by chrisvanpatten** [comment] 2019-05-13 17:25
Another +1 — we'd love to use this too but this error is preventing us from getting the orb to work.

**Closed** 2019-05-20 13:29 UTC
